export default {
  FETCH_HOME_PAGE_CONTENT_LIST_START: "FETCH_HOME_PAGE_CONTENT_LIST_START",
  FETCH_HOME_PAGE_CONTENT_LIST_SUCCESS: "FETCH_HOME_PAGE_CONTENT_LIST_SUCCESS",
  FETCH_HOME_PAGE_CONTENT_LIST_FAIL: "FETCH_HOME_PAGE_CONTENT_LIST_FAIL",
};
