export default {
  FETCH_CONTENT_LIST_BY_MANUFACTOR_PATH_URL_START:
    "FETCH_CONTENT_LIST_BY_MANUFACTOR_PATH_URL_START",
  FETCH_CONTENT_LIST_BY_MANUFACTOR_PATH_URL_SUCCESS:
    "FETCH_CONTENT_LIST_BY_MANUFACTOR_PATH_URL_SUCCESS",
  FETCH_CONTENT_LIST_BY_MANUFACTOR_PATH_URL_FAIL:
    "FETCH_CONTENT_LIST_BY_MANUFACTOR_PATH_URL_FAIL",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  FETCH_PRODUCT_LIST_START: "FETCH_PRODUCT_LIST_START",
  FETCH_PRODUCT_LIST_SUCCESS: "FETCH_PRODUCT_LIST_SUCCESS",
  FETCH_PRODUCT_LIST_FAIL: "FETCH_PRODUCT_LIST_FAIL",
};
