export default {
  FETCH_PRODUCT_TYPES_START: "FETCH_PRODUCT_TYPES_START",
  FETCH_PRODUCT_TYPES_SUCCESS: "FETCH_PRODUCT_TYPES_SUCCESS",
  FETCH_PRODUCT_TYPES_FAIL: "FETCH_PRODUCT_TYPES_FAIL",
  ADD_PRODUCT_TYPES_START: "ADD_PRODUCT_TYPES_START",
  ADD_PRODUCT_TYPES_SUCCESS: "ADD_PRODUCT_TYPES_SUCCESS",
  ADD_PRODUCT_TYPES_FAIL: "ADD_PRODUCT_TYPES_FAIL",
};
