export default {
  FETCH_CONTENT_LIST_BY_CATEGORY_PATH_URL_START:
    "FETCH_CONTENT_LIST_BY_CATEGORY_PATH_URL_START",
  FETCH_CONTENT_LIST_BY_CATEGORY_PATH_URL_SUCCESS:
    "FETCH_CONTENT_LIST_BY_CATEGORY_PATH_URL_SUCCESS",
  FETCH_CONTENT_LIST_BY_CATEGORY_PATH_URL_FAIL:
    "FETCH_CONTENT_LIST_BY_CATEGORY_PATH_URL_FAIL",
  FETCH_PRODUCTS_BASE_ON_CATEGORY_PATH_URL_AND_PAGE_START:
    "FETCH_PRODUCTS_BASE_ON_CATEGORY_PATH_URL_AND_PAGE_START",
  FETCH_PRODUCTS_BASE_ON_CATEGORY_PATH_URL_AND_PAGE_SUCCESS:
    "FETCH_PRODUCTS_BASE_ON_CATEGORY_PATH_URL_AND_PAGE_SUCCESS",
  FETCH_PRODUCTS_BASE_ON_CATEGORY_PATH_URL_AND_PAGE_FAIL:
    "FETCH_PRODUCTS_BASE_ON_CATEGORY_PATH_URL_AND_PAGE_START",
};
