const orderedActionTypes = {
  FETCH_ORDERED_LIST_START: "FETCH_ORDERED_LIST_START",
  FETCH_ORDERED_LIST_SUCCESS: "FETCH_ORDERED_LIST_SUCCESS",
  FETCH_ORDERED_LIST_FAIL: "FETCH_ORDERED_LIST_FAIL",
};

export default orderedActionTypes;
