export default {
  TOGGLE_CART: "TOGGLE_CART",
  CLOSE_CART: "CLOSE_CART",
  ADD_ITEM: "ADD_ITEM",
  INCREASE_ITEM: "INCREASE_ITEM",
  DECREASE_ITEM: "DECREASE_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_CART_ITEMS: "CLEAR_CART_ITEMS",
  SET_CART_CHECKOUT_POSITION: "SET_CART_CHECKOUT_POSITION",
  ORDERED_DETAIL: "ORDERED_DETAIL",
  SET_METHOD_DELIVERY: "SET_METHOD_DELIVERY",
};
