export default {
  FETCH_PRODUCT_COMMENT_REVIEW_START: "FETCH_PRODUCT_COMMENT_REVIEW_START",
  FETCH_PRODUCT_COMMENT_REVIEW_SUCCESS: "FETCH_PRODUCT_COMMENT_REVIEW_SUCCESS",
  FETCH_PRODUCT_COMMENT_REVIEW_FAIL: "FETCH_PRODUCT_COMMENT_REVIEW_FAIL",
};
