export default {
  FETCH_PRODUCT_DETAIL_START: "FETCH_PRODUCT_DETAIL_START",
  FETCH_PRODUCT_DETAIL_SUCCESS: "FETCH_PRODUCT_DETAIL_SUCCESS",
  FETCH_PRODUCT_DETAIL_FAIL: "FETCH_PRODUCT_DETAIL_FAIL",
};
