export default {
  FETCH_CONTENT_LIST_BY_PRODUCT_GROUP_START:
    "FETCH_CONTENT_LIST_BY_PRODUCT_GROUP_START",
  FETCH_CONTENT_LIST_BY_PRODUCT_GROUP_SUCCESS:
    "FETCH_CONTENT_LIST_BY_PRODUCT_GROUP_SUCCESS",
  FETCH_CONTENT_LIST_BY_PRODUCT_GROUP_FAIL:
    "FETCH_CONTENT_LIST_BY_PRODUCT_GROUP_FAIL",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  FETCH_PRODUCT_LIST_START: "FETCH_PRODUCT_LIST_START",
  FETCH_PRODUCT_LIST_SUCCESS: "FETCH_PRODUCT_LIST_SUCCESS",
  FETCH_PRODUCT_LIST_FAIL: "FETCH_PRODUCT_LIST_FAIL",
  FILTER_PRODUCTS_BY_PRICE_START: "FILTER_PRODUCTS_BY_PRICE_START",
  FILTER_PRODUCTS_BY_PRICE_SUCCESS: "FILTER_PRODUCTS_BY_PRICE_SUCCESS",
  FILTER_PRODUCTS_BY_PRICE_FAIL: "FILTER_PRODUCTS_BY_PRICE_FAIL",
};
