export default {
  FETCH_PRODUCT_TYPE_LIST_START: "FETCH_PRODUCT_TYPE_LIST_START",
  FETCH_PRODUCT_TYPE_LIST_SUCCESS: "FETCH_PRODUCT_TYPE_LIST_SUCCESS",
  FETCH_PRODUCT_TYPE_LIST_FAIL: "FETCH_PRODUCT_TYPE_LIST_FAIL",
};
