export default {
  FETCH_CATEGORY_START: "FETCH_CATEGORY_START",
  FETCH_CATEGORY_SUCCESS: "FETCH_CATEGORY_SUCCESS",
  FETCH_CATEGORY_FAIL: "FETCH_CATEGORY_FAIL",
  SEARCH_CATEGORY: "SEARCH_CATEGORY",
};
